version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dgs-graphql-db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  postgresql_data:
